# This file is a template, and might need editing before it works on your project.
# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ce/pages/
image: ruby:2.5

variables:
  JEKYLL_ENV: production

cache:
  paths:
    - vendor/

before_script:
  - export LANG="en_US.UTF-8"
  - gem update --system --no-doc
  - bundle install --path vendor

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -V -t -d public
  artifacts:
    paths:
    - public
  only:
    - master

